-- Check constraints not generated by Prisma — applied manually

-- Role: default roles have no entity; custom roles always have one
ALTER TABLE "Role" ADD CONSTRAINT "chk_role_default_entity"
  CHECK (("isDefault" = TRUE AND "entityId" IS NULL) OR ("isDefault" = FALSE AND "entityId" IS NOT NULL));

-- UserRole: only valid role targets
ALTER TABLE "UserRole" ADD CONSTRAINT "chk_role_entity_type"
  CHECK ("entityType" IN ('HUB', 'COMMUNITY'));

-- Hub: valid geographic bounds
ALTER TABLE "Hub" ADD CONSTRAINT "chk_hub_lat"
  CHECK ("latitude" BETWEEN -90 AND 90);
ALTER TABLE "Hub" ADD CONSTRAINT "chk_hub_lng"
  CHECK ("longitude" BETWEEN -180 AND 180);

-- Event: end must be after start
ALTER TABLE "Event" ADD CONSTRAINT "chk_event_dates"
  CHECK ("endsAt" IS NULL OR "endsAt" > "startsAt");

-- Comment: only valid parent entity types
ALTER TABLE "Comment" ADD CONSTRAINT "chk_comment_entity_type"
  CHECK ("parentEntityType" IN ('ANNOUNCEMENT', 'EVENT'));

-- Subscription: inactive subscriptions must have an unsubscribed timestamp
ALTER TABLE "Subscription" ADD CONSTRAINT "chk_unsub_timestamp"
  CHECK ("isActive" = TRUE OR "tsUnsubscribed" IS NOT NULL);
